# This file was generated by GoReleaser. DO NOT EDIT.
cask "homebrew-tap" do
  desc "Organize your Product Requirements Document (PRD)"
  homepage "https://traceable.dev"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "homebrew-tap"

  on_macos do
    on_intel do
      url "https://github.com/techcorrectco/homebrew-tap/releases/download/v0.1.0/traceable_Darwin_x86_64.tar.gz"
      sha256 "4069c994c27f599a847ece50f6c53db042f773f537ba94aab41140f165651914"
    end
    on_arm do
      url "https://github.com/techcorrectco/homebrew-tap/releases/download/v0.1.0/traceable_Darwin_arm64.tar.gz"
      sha256 "ddbe83a50cf9188332612e385bdf6049fb0ea3a9df3403942d6ee0bcab42a721"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/techcorrectco/homebrew-tap/releases/download/v0.1.0/traceable_Linux_x86_64.tar.gz"
      sha256 "5bfb92db3157bbe7d774a262890cac1fd76b1e9682ce6faaf21089846c2c0601"
    end
    on_arm do
      url "https://github.com/techcorrectco/homebrew-tap/releases/download/v0.1.0/traceable_Linux_arm64.tar.gz"
      sha256 "6871674364faf6292e085ae3c3505a103d685aefc36dcb6c288bbeff309e55a9"
    end
  end

  # No zap stanza required
end
