# This file was generated by GoReleaser. DO NOT EDIT.
cask "traceable" do
  desc "Organize your Product Requirements Document (PRD)"
  homepage "https://traceable.dev"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "traceable"

  on_macos do
    on_intel do
      url "https://github.com/techcorrectco/homebrew-tap/releases/download/v0.1.0/traceable_Darwin_x86_64.tar.gz"
      sha256 "7c240053423d9e6004069c69e73ae553a760011a534b9ba5b292d57d66675e39"
    end
    on_arm do
      url "https://github.com/techcorrectco/homebrew-tap/releases/download/v0.1.0/traceable_Darwin_arm64.tar.gz"
      sha256 "7806e0aa2150b745a8be0db311727eeed6405e364b630053ba94eb675acf5aa0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/techcorrectco/homebrew-tap/releases/download/v0.1.0/traceable_Linux_x86_64.tar.gz"
      sha256 "4a0d59cd8ba315967c5032934a3a178acfd7b39191d5404e7f36a9130acb4a5d"
    end
    on_arm do
      url "https://github.com/techcorrectco/homebrew-tap/releases/download/v0.1.0/traceable_Linux_arm64.tar.gz"
      sha256 "6b26614a5c423a42d5109a3e87672e9f14346ff35c19872e2fa33598741c3bff"
    end
  end

  # No zap stanza required
end
